import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    productName: "Premium Wireless Headphones",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    primaryImage: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    description:
      "High-quality wireless headphones with noise cancellation, premium sound quality, and long battery life. Perfect for music lovers and professionals.",
    price: "299.99",
    material: "Premium Plastic & Metal",
    size: "Standard",
    weight: "250g",
    discount: "20",
    otherSpecification: "Bluetooth 5.0, 30-hour battery life, Active noise cancellation",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    productName: "Smart Fitness Watch",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    primaryImage: "/placeholder.svg?height=400&width=400",
    category: "Wearables",
    description:
      "Advanced fitness tracking watch with heart rate monitoring, GPS, and smartphone connectivity. Track your health and stay connected.",
    price: "199.99",
    material: "Aluminum & Silicone",
    size: "42mm",
    weight: "45g",
    discount: "15",
    otherSpecification: "Water resistant, 7-day battery, Health monitoring sensors",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "3",
    productName: "Ergonomic Office Chair",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    primaryImage: "/placeholder.svg?height=400&width=400",
    category: "Furniture",
    description:
      "Professional ergonomic office chair designed for comfort and productivity. Adjustable height, lumbar support, and premium materials.",
    price: "449.99",
    material: "Mesh & Steel Frame",
    size: "Standard",
    weight: "18kg",
    discount: "10",
    otherSpecification: "Adjustable armrests, 360° swivel, Weight capacity: 150kg",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "4",
    productName: "Portable Bluetooth Speaker",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    primaryImage: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    description:
      "Compact and powerful Bluetooth speaker with exceptional sound quality. Perfect for outdoor activities and home entertainment.",
    price: "89.99",
    material: "Durable Plastic",
    size: "Compact",
    weight: "500g",
    discount: "25",
    otherSpecification: "IPX7 waterproof, 12-hour battery, LED light show",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: "5",
    productName: "Gaming Mechanical Keyboard",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    primaryImage: "/placeholder.svg?height=400&width=400",
    category: "Gaming",
    description:
      "High-performance mechanical gaming keyboard with RGB backlighting and tactile switches. Built for competitive gaming and productivity.",
    price: "159.99",
    material: "Aluminum Frame",
    size: "Full Size",
    weight: "1.2kg",
    discount: "30",
    otherSpecification: "Cherry MX switches, RGB lighting, Anti-ghosting",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "6",
    productName: "Stainless Steel Water Bottle",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    primaryImage: "/placeholder.svg?height=400&width=400",
    category: "Lifestyle",
    description:
      "Premium insulated stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12 hours. Eco-friendly and durable.",
    price: "34.99",
    material: "Stainless Steel",
    size: "750ml",
    weight: "350g",
    discount: "0",
    otherSpecification: "Double-wall insulation, BPA-free, Leak-proof cap",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-28"),
  },
]

export const categories = ["All", "Electronics", "Wearables", "Furniture", "Gaming", "Lifestyle"]
